FROM python:3.13-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

WORKDIR /app

COPY pyproject.toml uv.lock ./
COPY packages packages

RUN uv sync --frozen

EXPOSE 8000

CMD ["uv", "run", "fastapi", "dev", "packages/gbp-server/src/gbp_server", "--host", "0.0.0.0"]
