FROM python:3.13-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

WORKDIR /app

COPY pyproject.toml uv.lock ./
COPY packages packages

RUN uv sync --frozen

EXPOSE 8000

CMD ["uv", "run", "uvicorn", "gbp.server:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--reload-dir", "packages", "--log-level", "debug"]
